### ISSUE TITLE
Traducción sección Docker

### ISSUE THREAD

**Issue by rje1974** [rje1974/ROS_Es#3]
Estoy trabajando en este documente.. https://wiki.ros.org/es/docker/Tutorials/Docker

**Comment by matiasbavera** [comment]
Donde te puedo poner algunas sugerencias? por acá?

**Comment by rje1974** [comment]
Por supuesto.. Si tienen que ver con la traducción de docker...

**Comment by matiasbavera** [comment]
> Por razones que vas a entenderás próximamente, no es requerida una instalación base de ROS en tu sistema, salvo que se lo pida expresamente. Para que entiendas rápido como esto es posible con Docker, se te recomienda que lo utilices en este tutorial online.

Por razones que serán explicadas más adelante en este tutorial,  no es requerida una instalación base de ROS en tu sistema, salvo que se lo pida expresamente. Para que entiendas rápido como esto es posible con **Docker**, se recomienda que lo utilices en este tutorial online.

**Comment by matiasbavera** [comment]
> Las instrucción de instalación están disponibles para múltiples sistemas operativos, incluyendo Ubuntu, Mac OS x, Debian, Fedora y hasta Microsoft Windows. ¯\_(ツ)_/¯ siendo esta la mejor forma de usar ROS en W10.

Las instrucciones de instalación están disponibles para múltiples sistemas operativos, incluyendo Ubuntu, Mac OS x, Debian, Fedora y hasta Microsoft Windows. ¯\_(ツ)_/¯ . siendo esta la mejor forma de usar ROS en W10.


> siendo esta la mejor forma de usar ROS en W10.

Por lo que habían dicho en el grupo, creo que vale la pena aclarar que tiene que ser Windows 10 pro. O puede que esta información esté desactualizada

**Comment by matiasbavera** [comment]
![image](https://user-images.githubusercontent.com/11761240/109008079-a5da2200-768b-11eb-8bfd-72a8cbc67dc8.png)

El título debería ser Usando las imágenes de ROS. Porque en teoría vos estás bajando imágenes que ya tienen ROS instalado como dependencias

**Comment by matiasbavera** [comment]
![image](https://user-images.githubusercontent.com/11761240/109008225-d457fd00-768b-11eb-87ba-c620a77beb1c.png)
Imagenes del Repositorio oficial de ROS?

**Comment by matiasbavera** [comment]
> Usando el nombre del contenedor mediante ID que mientras escribimos este tutorial se llamó "nostalgic_morse", podemos llamar una sesion adicional de bash del mismo contenedor corriendo:

Usando el nombre del contenedor como ID, que cuando escribimos este tutorial a Docker se le ocurrió asignar el string "nostalgic_morse", podemos llamar una sesion adicional de bash del mismo contenedor corriendo:

**Comment by matiasbavera** [comment]
Dejé un par de comentarios. Saludos. 

PD: no me está funcionando el flameshot

**Comment by rje1974** [comment]
> > Las instrucción de instalación están disponibles para múltiples sistemas operativos, incluyendo Ubuntu, Mac OS x, Debian, Fedora y hasta Microsoft Windows. ¯_(ツ)_/¯ siendo esta la mejor forma de usar ROS en W10.
> 
> Las instrucciones de instalación están disponibles para múltiples sistemas operativos, incluyendo Ubuntu, Mac OS x, Debian, Fedora y hasta Microsoft Windows. ¯_(ツ)_/¯ . siendo esta la mejor forma de usar ROS en W10.
> 
> > siendo esta la mejor forma de usar ROS en W10.
> 
> Por lo que habían dicho en el grupo, creo que vale la pena aclarar que tiene que ser Windows 10 pro. O puede que esta información esté desactualizada

Lo de w10 pro esta desactualizado.. Yo hice la instalacion en un home

**Comment by rje1974** [comment]
> Usando el nombre del contenedor como ID, que cuando escribimos este tutorial a Docker se le ocurrió asignar el string "nostalgic_morse", podemos llamar una sesion adicional de bash del mismo contenedor corriendo:

liquidado

**Comment by rje1974** [comment]
> ![image](https://user-images.githubusercontent.com/11761240/109008225-d457fd00-768b-11eb-87ba-c620a77beb1c.png)
> Imagenes del Repositorio oficial de ROS?

liquidado

**Comment by rje1974** [comment]
> ![image](https://user-images.githubusercontent.com/11761240/109008225-d457fd00-768b-11eb-87ba-c620a77beb1c.png)
> Imagenes del Repositorio oficial de ROS?

liquidado

**Comment by rje1974** [comment]
> ![image](https://user-images.githubusercontent.com/11761240/109008079-a5da2200-768b-11eb-8bfd-72a8cbc67dc8.png)
> 
> El título debería ser Usando las imágenes de ROS. Porque en teoría vos estás bajando imágenes que ya tienen ROS instalado como dependencias

liquidado
